<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Tenant</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>a62d9de9-4494-4fab-b195-d24dee424be7</testSuiteGuid>
   <testCaseLink>
      <guid>882e38dc-b707-4570-8580-9f9f7a443f7f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Tenant/RegisterTenant</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e25d6a6a-b4b0-41dd-bbf5-9b434b6d12ff</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Test Data Tenant1</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>e25d6a6a-b4b0-41dd-bbf5-9b434b6d12ff</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>emailName</value>
         <variableId>80cd594e-34e4-4e2f-b7a4-41b3974aa616</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b371a7a-a76c-4f61-878e-7ce63dafc39f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>150db23a-5698-46e5-b779-03f52c3fc131</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d3d67c8-34f9-4f60-8dff-9ccad2fcad99</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5ae3e00-0c81-40f9-889b-8995a78306ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b0f21a1-7561-4ca5-8d9f-1080192cbaaa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c481d702-321a-492c-9418-c832d91b24ce</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7c29e379-7c0f-40a9-9117-65e75ff4a34c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Tenant/RegisterTenant_sai</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>7d967f62-9a57-48d9-9bdf-89bb7ba58fb0</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Test Data Tenant1</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>7d967f62-9a57-48d9-9bdf-89bb7ba58fb0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>emailName</value>
         <variableId>ba027e21-3e42-43e7-8931-0064d48f8b43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>126c6e56-2214-48fb-8e78-8604a692bc8f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f665f153-3176-4a24-8a75-92c7b5100c22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c77c187e-5d80-4662-b370-c9bbf420a6e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b48576c-4ca9-43dd-a4d2-dcefba727eba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>112cfa47-3576-4175-8523-4722c1ff9e0a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8b6c04d-18b8-4f27-bb9a-8f541db5344f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7ed446f1-6df9-43be-91bc-df947f30b08b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Tenant/KichHoatEmail</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6639ec6d-1613-4964-bdc0-6c7d414c066f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5ed772d-2f9e-4ba8-959e-5f065b4d76c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b6b2026-69fd-4d1b-a6fe-dd6f5bd68cf3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4f16a29-62be-4094-8376-4cd8b5cede5e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7dc5dd10-0604-4361-aa88-0da0fb33f778</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ec50693-5a6b-46bd-9a83-7813fb748d56</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c804407-70e7-4873-9474-09a644bf7c93</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6a55c41-1cfc-405a-b833-d31e322dee33</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f96620d5-ffb8-4e02-9ff2-8d046659a884</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Tenant/viewTenant</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4db479a9-e7bd-4035-bac8-91a69811fd9c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Test Data Tenant1</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>4db479a9-e7bd-4035-bac8-91a69811fd9c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>passwordTenant</value>
         <variableId>49b88f16-94d6-4f60-828d-7d5968d35449</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4db479a9-e7bd-4035-bac8-91a69811fd9c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>emailName</value>
         <variableId>eed4a9ad-082f-4221-9736-469e2c656c16</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a5c94e6c-41c0-41c8-a09a-20bc8641da8b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Tenant/viewTenantDetail</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e48f87e8-fa18-464f-af21-123b31beca23</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Test Data Tenant1</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44bcd495-d575-4b2c-80fc-2c4465ff619f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e48f87e8-fa18-464f-af21-123b31beca23</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>emailName</value>
         <variableId>69ea316f-e840-4b53-a663-0f7fb63d69a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e48f87e8-fa18-464f-af21-123b31beca23</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>passwordTenant</value>
         <variableId>ede87687-a3fc-4bd7-b737-b6fe1bb7c295</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2d48d688-9488-472e-b5e4-30eb98fbdd70</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Tenant/EditTenant_saiName</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e2a931eb-dff0-47e2-a896-278841fcbe27</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Test Data Tenant1</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>e2a931eb-dff0-47e2-a896-278841fcbe27</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>emailName</value>
         <variableId>19dc3e1f-da64-47d4-a373-324d5c78c819</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e2a931eb-dff0-47e2-a896-278841fcbe27</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>passwordTenant</value>
         <variableId>7c5577ab-054c-4ada-a9ae-2af3896408de</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>97d6c25b-b573-4247-b27c-7e4057c32f08</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Tenant/DeleteTenant</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>140ff363-1fe0-46cb-a1c3-e19b815e71be</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Test Data Tenant1</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>140ff363-1fe0-46cb-a1c3-e19b815e71be</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>emailName</value>
         <variableId>7f4efcc8-f4f6-4e91-887e-3d288a550e4c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>140ff363-1fe0-46cb-a1c3-e19b815e71be</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>passwordTenant</value>
         <variableId>52af7287-844b-4d26-b56b-ba1bf2d1a174</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
