<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_EVNHNI_C01EVNHNI_C02EVNHNI_C03EVNHNI_C0_62e982</name>
   <tag></tag>
   <elementGuidId>ee414c45-86ef-428d-9eff-994aa4ede92b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.selectize-control.rateObjectslt.multi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rateObject']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectize-control rateObjectslt multi</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EVNHNI_C01EVNHNI_C02EVNHNI_C03EVNHNI_C04EVNHNI_C06EVNHNI_C07EVNHNI_C13EVNHNI_C14EVNHNI_C17EVNHNI_C18EVNHNI_C19EVNHNI_C20EVNHNI_C21EVNHNI_C25EVNHNI_C26EVNHNI_C27EVNHNI_C29C29lathuhangCTY_GP_antoanEVN_HNI_TESTCongtyABCEVNHNI_C09EVNHNI_C28evn1_hnievn2_hnievn3_hniEVN_HNIngovnpmtkhdnkhdn1vnpt32VTU_NGUYENCHAULONGlqui_aggEVNHNI_C05EVNHNI_C08EVNHNI_C10EVNHNI_C11EVNHNI_C12EVNHNI_C15EVNHNI_C16EVNHNI_C22EVNHNI_C23EVNHNI_C24EVNHNI_C30demotinhnanggd2vinhhienjvasiaG-Innovationsth_so_vetinh_vntongcuchaiquantruyenthongtnttctvantaihndn2_cty_binh_anhdn1_cty_trung_tindn2_ptcndt_binhanhdddtphanoiadminbinhanhdn1_cty_ict_quocgiaEVNSPChenry_eup_net_vndn2_npcit_2Evnnpc2skysoftIgoteldn2_npcitd1_cty_sessesdn2_tstatcom_testquangndMobile_VPNddk_hniNLDKmenntkhhn1HuyenCustomernghiepnvkhachhn3sinhnvkhachhn1khachhn2menntkhhn2menntkhxoa2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rateObject&quot;)/div[@class=&quot;selectize-control rateObjectslt multi&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rateObject']/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(*)'])[7]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div</value>
   </webElementXpaths>
</WebElementEntity>
