<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Chn tt c32928SIMs_uk-icon-trash-o white</name>
   <tag></tag>
   <elementGuidId>14f1613b-25ff-4a59-a111-278930b039fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.uk-icon-trash-o.white</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmSubscriptionAction']/div[2]/div/div/div/div[2]/div/div[3]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uk-icon-trash-o white</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmSubscriptionAction&quot;)/div[@class=&quot;md-card uk-margin-medium-bottom&quot;]/div[@class=&quot;md-card-content&quot;]/div[@class=&quot;uk-overflow-container&quot;]/div[@class=&quot;uk-grid&quot;]/div[@class=&quot;uk-width-medium-3-5&quot;]/div[@class=&quot;uk-grid&quot;]/div[@class=&quot;uk-width-medium-1-3 uk-width-small-1-1&quot;]/a[@class=&quot;md-btn md-btn-block md-btn-danger md-btn-wave-light waves-effect waves-button waves-light&quot;]/i[@class=&quot;uk-icon-trash-o white&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSubscriptionAction']/div[2]/div/div/div/div[2]/div/div[3]/a/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/i</value>
   </webElementXpaths>
</WebElementEntity>
