<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Loi khch hng_dense-image dense-loading</name>
   <tag></tag>
   <elementGuidId>80dd3222-ff2e-4317-b032-11c547174444</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.md-btn.md-btn-block.md-btn-success.md-btn-wave-light.waves-effect.waves-button.waves-light > img.dense-image.dense-loading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmRatingRate']/div/div/div/div[2]/div[4]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/theme/assets/photo/search.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dense-image dense-loading</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmRatingRate&quot;)/div[@class=&quot;md-card&quot;]/div[@class=&quot;md-card-content large-padding&quot;]/div[@class=&quot;uk-form-row&quot;]/div[@class=&quot;uk-grid&quot;]/div[@class=&quot;uk-width-medium-1-6 uk-width-small-1-3  uk-text-right input-padding-common&quot;]/a[@class=&quot;md-btn md-btn-block md-btn-success md-btn-wave-light waves-effect waves-button waves-light&quot;]/img[@class=&quot;dense-image dense-loading&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmRatingRate']/div/div/div/div[2]/div[4]/a/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a/img</value>
   </webElementXpaths>
</WebElementEntity>
