<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__md-user-image dense-image dense-loading (1)</name>
   <tag></tag>
   <elementGuidId>f471e0ad-a69d-4119-bc11-4daf4426a3fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.md-user-image.dense-image.dense-loading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header_main']/div/nav/div[2]/ul/li[3]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md-user-image dense-image dense-loading</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/theme/assets/img/avatars/avatar_11_tn.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header_main&quot;)/div[@class=&quot;header_main_content&quot;]/nav[@class=&quot;uk-navbar&quot;]/div[@class=&quot;uk-navbar-flip&quot;]/ul[@class=&quot;uk-navbar-nav user_actions&quot;]/li[3]/a[@class=&quot;user_action_image&quot;]/img[@class=&quot;md-user-image dense-image dense-loading&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header_main']/div/nav/div[2]/ul/li[3]/a/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
   </webElementXpaths>
</WebElementEntity>
