<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cac quyen co san_fancytree-checkbox</name>
   <tag></tag>
   <elementGuidId>14b7af61-7b5f-44c4-b430-25036bc56bca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.fancytree-checkbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tFilter']/ul/li/span/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fancytree-checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tFilter&quot;)/ul[@class=&quot;ui-fancytree fancytree-container fancytree-plain fancytree-treefocus&quot;]/li[@class=&quot;fancytree-lastsib&quot;]/span[@class=&quot;fancytree-node fancytree-expanded fancytree-folder fancytree-has-children fancytree-lastsib fancytree-exp-el fancytree-ico-ef&quot;]/span[@class=&quot;fancytree-checkbox&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tFilter']/ul/li/span/span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span[2]</value>
   </webElementXpaths>
</WebElementEntity>
