<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_danh sach quyen da chon</name>
   <tag></tag>
   <elementGuidId>e1219f2e-05d5-4a0d-b771-f35aea1f1b0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.ui-fancytree.fancytree-container.fancytree-plain.fancytree-treefocus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tFilter_selected']/ul</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-fancytree fancytree-container fancytree-plain fancytree-treefocus</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Quản Trị Hệ ThốngNgười DùngTạoXemCập NhậtXóaVai TròTạoXemCập NhậtXóaQuyềnXemTenantTạoXemCập NhậtXóaCài Đặt Thông BáoXemCập NhậtLogXemXóaApplicationTạoXemCập NhậtXóaDeviceTạoXemCập NhậtXóaData Mgt TemplateTạoXemCập NhậtXóaData Mgt DashboardTạoXemCập NhậtXóaGroupTạoXemCập NhậtXóaData Mgt WidgetTạoXemCập NhậtXóaIPEXemTạoXóaDeviceTemplateTạo</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tFilter_selected&quot;)/ul[@class=&quot;ui-fancytree fancytree-container fancytree-plain fancytree-treefocus&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tFilter_selected']/ul</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Các quyền đã chọn'])[1]/following::ul[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;&lt;'])[1]/following::ul[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div/ul</value>
   </webElementXpaths>
</WebElementEntity>
